# Generated by Django 4.2.15 on 2024-08-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_created_by_post_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Check this box to publish this post.'),
        ),
    ]
