# Generated by Django 4.2.15 on 2024-08-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Check this box to publish this page.'),
        ),
    ]
